const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+Math.random().toString(16).slice(2);
let state={tasks:[],events:[],categories:['Grants & Compliance','Reporting & Analytics','Operations Support & Data Collection','Training & Internal Processes','Data Systems Management'],wizard:{event:null,q:0,answers:[],suggestions:[]}};
const qs={
 deadline:[
 ['Do you need to collect program, attendance, outcome, or participant data before this deadline?',[['Yes','Request and compile required program/outcome data',14],['No',null]]],
 ['Will Finance or another department need to provide documentation or numbers?',[['Yes','Request required financial/supporting documentation',14],['No',null]]],
 ['Does the submission require a narrative, application, or report to be drafted?',[['Yes','Draft grant narrative / report',10],['No',null]]],
 ['Should leadership review or approve the submission before it is final?',[['Yes','Send draft for leadership review and approval',5],['No',null]]],
 ['Do attachments, signatures, or portal requirements need a final check?',[['Yes','Complete final QA of attachments, signatures, and portal requirements',2],['No',null]]],
 ['Would you like a final submission task on the event date?',[['Yes','Submit grant deliverable',0],['No',null]]]],
 site:[
 ['Do staff need to prepare records, rosters, policies, or supporting documentation for the visit?',[['Yes','Assemble site visit documentation and records',10],['No',null]]],
 ['Should program/facility staff receive a readiness check before the visit?',[['Yes','Complete site visit readiness check with staff',7],['No',null]]],
 ['Do you need to confirm logistics, location, access, or the visit agenda?',[['Yes','Confirm site visit logistics and agenda',5],['No',null]]],
 ['Would a final internal walkthrough be useful?',[['Yes','Conduct final site visit walkthrough',1],['No',null]]]],
 meeting:[
 ['Do you need to review prior materials or prepare an agenda before this meeting/training?',[['Yes','Prepare agenda and review meeting materials',3],['No',null]]],
 ['Do you need to gather data, questions, or updates to bring to the session?',[['Yes','Compile updates, questions, and supporting data',2],['No',null]]],
 ['Should there be a follow-up task after the event?',[['Yes','Document follow-up actions from meeting/training',-1],['No',null]]]],
 holiday:[['Are there deadlines or tasks immediately after this closure that should be moved earlier?',[['Yes','Review upcoming work and complete pre-closure preparations',2],['No',null]]]],
 general:[['Does this event require preparation in advance?',[['Yes','Prepare for '+ '{event}',5],['No',null]]],['Will someone else need information or a reminder before the event?',[['Yes','Send event information / reminder to stakeholders',2],['No',null]]],['Is follow-up work likely after the event?',[['Yes','Complete follow-up actions for '+ '{event}',-1],['No',null]]]]};
function saveLocal(){localStorage.setItem('codexClipboardV1',JSON.stringify(state))} function loadLocal(){try{Object.assign(state,JSON.parse(localStorage.getItem('codexClipboardV1'))||{})}catch(e){}}
function dateOnly(v){if(!v)return''; if(v instanceof Date)return v.toISOString().slice(0,10); let d=new Date(v);return isNaN(d)?String(v).slice(0,10):d.toISOString().slice(0,10)}
function pretty(d){if(!d)return'—';let x=new Date(d+'T12:00:00');return x.toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}
function render(){renderCats();renderTasks();renderDaily();renderDeadlines();saveLocal()}
function renderCats(){let cats=[...new Set([...state.categories,...state.tasks.map(t=>t.category).filter(Boolean)])];$('#catFilter').innerHTML='<option>All Categories</option>'+cats.map(x=>`<option>${esc(x)}</option>`).join('');$('#categories').innerHTML=cats.map(x=>`<option value="${esc(x)}">`).join('')}
function renderTasks(){let q=$('#search').value.toLowerCase(),sf=$('#statusFilter').value,cf=$('#catFilter').value;let rows=state.tasks.filter(t=>(!q||(t.name+' '+(t.notes||'')).toLowerCase().includes(q))&&(sf==='All Statuses'||t.status===sf)&&(cf==='All Categories'||t.category===cf)).sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999'));$('#taskRows').innerHTML=rows.length?rows.map(t=>`<tr><td><input type="checkbox" ${t.status==='Completed'?'checked':''} onchange="toggleDone('${t.id}',this.checked)"></td><td><b>${esc(t.name)}</b>${t.event?`<br><small>${esc(t.event)}</small>`:''}</td><td>${pretty(t.due)}</td><td>${esc(t.category||'—')}</td><td class="priority ${t.priority}">${t.priority}</td><td>${esc(t.time||'—')}</td><td><span class="badge">${t.status}</span></td><td class="row-actions"><button onclick="editTask('${t.id}')">Edit</button> <button onclick="delTask('${t.id}')">×</button></td></tr>`).join(''):'<tr><td colspan="8">No tasks yet. Add one manually or create tasks from a Calendar event.</td></tr>';let today=new Date().toISOString().slice(0,10);let overdue=state.tasks.filter(t=>t.due&&t.due<today&&t.status!=='Completed').length;$('#stats').innerHTML=`<div class=stat><b>${state.tasks.length}</b><span>Total Tasks</span></div><div class=stat><b>${state.tasks.filter(t=>t.status==='Completed').length}</b><span>Completed</span></div><div class=stat><b>${state.tasks.filter(t=>t.status==='In Progress').length}</b><span>In Progress</span></div><div class=stat><b>${overdue}</b><span>Overdue</span></div>`}
function renderDaily(){let d=$('#dailyDate').value;let arr=state.tasks.filter(t=>t.due===d);$('#dailyCards').innerHTML=arr.length?arr.map(t=>`<div><h3>${esc(t.name)}</h3><span class=badge>${t.status}</span> · ${esc(t.category||'Uncategorized')} · ${esc(t.time||'No time estimate')}<p>${esc(t.notes||'')}</p></div>`).join(''):'<div>No tasks scheduled for this date.</div>'}
function renderDeadlines(){let arr=state.events.filter(e=>/deadline/i.test(e.category||'')&&e.status!=='cancelled').sort((a,b)=>a.start.localeCompare(b.start));$('#deadlineCards').innerHTML=arr.length?arr.map(e=>{let n=state.tasks.filter(t=>t.event===e.name&&t.status!=='Completed').length;return `<div><h3>${esc(e.name)}</h3><b>${pretty(e.start)}</b> · ${esc(e.org||'')}<p>${esc(e.description||'')}</p><span class=badge>${n} open task${n===1?'':'s'}</span></div>`}).join(''):'<div>Import a Grant Calendar to populate deadline events.</div>'}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
window.toggleDone=(id,on)=>{let t=state.tasks.find(x=>x.id===id);t.status=on?'Completed':'Not Started';render()};window.delTask=id=>{state.tasks=state.tasks.filter(x=>x.id!==id);render()};window.editTask=id=>openTask(state.tasks.find(x=>x.id===id));
function openTask(t={}){$('#taskDialogTitle').textContent=t.id?'Edit Task':'Add Task';$('#editId').value=t.id||'';$('#taskName').value=t.name||'';$('#taskDue').value=t.due||'';$('#taskCategory').value=t.category||'Grants & Compliance';$('#taskPriority').value=t.priority||'Medium';$('#taskTime').value=t.time||'';$('#taskStatus').value=t.status||'Not Started';$('#taskEvent').value=t.event||'';$('#taskNotes').value=t.notes||'';$('#taskDialog').showModal()}
$('#addTaskBtn').onclick=()=>openTask();$('#saveTask').onclick=e=>{e.preventDefault();if(!$('#taskName').value.trim())return;let id=$('#editId').value;let t={id:id||uid(),name:$('#taskName').value.trim(),due:$('#taskDue').value,category:$('#taskCategory').value,priority:$('#taskPriority').value,time:$('#taskTime').value,status:$('#taskStatus').value,event:$('#taskEvent').value,notes:$('#taskNotes').value};if(id)state.tasks[state.tasks.findIndex(x=>x.id===id)]=t;else state.tasks.push(t);$('#taskDialog').close();render()};
$$('.nav').forEach(b=>b.onclick=()=>{$$('.nav').forEach(x=>x.classList.remove('active'));$$('.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.view).classList.add('active');if(b.dataset.view==='calendar')renderWizard()});['search','statusFilter','catFilter'].forEach(id=>$('#'+id).oninput=renderTasks);$('#dailyDate').value=new Date().toISOString().slice(0,10);$('#dailyDate').onchange=renderDaily;
$('#calendarFile').onchange=async e=>{let f=e.target.files[0];if(!f)return;try{let events=[];if(f.name.toLowerCase().endsWith('.json')){let j=JSON.parse(await f.text());events=(j.events||[]).map(normalizeEvent)}else{let buf=await f.arrayBuffer(),wb=XLSX.read(buf,{type:'array',cellDates:true}),ws=wb.Sheets['Events']||wb.Sheets[wb.SheetNames[0]],rows=XLSX.utils.sheet_to_json(ws,{defval:''});events=rows.map(r=>normalizeEvent({'name':r['Event Name']||r.Name,'org':r['Grant / Organization']||r.Organization,'category':r.Category,'status':r.Status,'start':r['Start Date']||r.Date,'end':r['End Date'],'description':r.Description,'notes':r.Notes})).filter(x=>x.name&&x.start)}state.events=events.filter(e=>e.status!=='cancelled');$('#importInfo').textContent=`Imported ${state.events.length} active calendar events from ${f.name}. Select an event below.`;state.wizard={event:null,q:0,answers:[],suggestions:[]};renderWizard();render()}catch(err){$('#importInfo').textContent='Could not read that file. Use the Codex Calendar Tool Events worksheet or a saved Calendar JSON project.'}};
function normalizeEvent(e){return{name:e.name||e.title||e.eventName||'',org:e.org||e.organization||e.grant||'',category:e.category||'',status:String(e.status||'confirmed').toLowerCase(),start:dateOnly(e.start||e.startDate||e.date),end:dateOnly(e.end||e.endDate),description:e.description||'',notes:e.notes||''}}
function questionSet(e){let c=(e.category||'').toLowerCase();return c.includes('site')?qs.site:c.includes('deadline')?qs.deadline:c.includes('meeting')||c.includes('training')?qs.meeting:c.includes('holiday')||c.includes('organization')?qs.holiday:qs.general}
function renderWizard(){let w=state.wizard,b=$('#wizardBody');if(!state.events.length){b.innerHTML='<h3>No calendar events loaded</h3><p>Import the Calendar Tool sample file to start the guided task discovery workflow.</p>';return}if(!w.event){b.innerHTML='<h3>Select a Calendar Event</h3><div class=event-list>'+state.events.map((e,i)=>`<div class=event onclick="selectEvent(${i})"><b>${esc(e.name)}</b><br><small>${pretty(e.start)} · ${esc(e.category)}</small></div>`).join('')+'</div>';setStep(0);return}let set=questionSet(w.event);if(w.q<set.length){let q=set[w.q];b.innerHTML=`<div class=question><small>${esc(w.event.name)} · Question ${w.q+1} of ${set.length}</small><h3>${esc(q[0])}</h3><div class=question-actions>${q[1].map((a,i)=>`<button class="${i===0?'primary':'ghost'}" onclick="answerQ(${i})">${esc(a[0])}</button>`).join('')}<button class=ghost onclick="passQ()">Pass</button><button class=linkbtn onclick="finishQuestions()">Skip to End</button></div></div>`;setStep(1);return}renderReview()}
window.selectEvent=i=>{state.wizard={event:state.events[i],q:0,answers:[],suggestions:[]};renderWizard()};window.answerQ=i=>{let w=state.wizard,set=questionSet(w.event),a=set[w.q][1][i];if(a[1])addSuggestion(a[1],a[2]);w.answers.push(a[0]);w.q++;renderWizard()};window.passQ=()=>{state.wizard.q++;renderWizard()};window.finishQuestions=()=>{state.wizard.q=999;renderReview()};$('#skipEnd').onclick=()=>{if(state.wizard.event)finishQuestions();else{$('.nav[data-view="tasks"]').click()}};
function addSuggestion(name,offset){let e=state.wizard.event,d=new Date(e.start+'T12:00:00');d.setDate(d.getDate()-(offset||0)); if(offset<0)d=new Date(new Date(e.start+'T12:00:00').getTime()+Math.abs(offset)*86400000);state.wizard.suggestions.push({id:uid(),name:name.replace('{event}',e.name),due:d.toISOString().slice(0,10),category:taskCat(e),priority:offset<=2?'High':'Medium',time:'0:30',status:'Not Started',event:e.name,notes:''})}
function taskCat(e){let c=(e.category||'').toLowerCase();return c.includes('deadline')?'Grants & Compliance':c.includes('site')?'Operations Support & Data Collection':c.includes('meeting')||c.includes('training')?'Training & Internal Processes':'Grants & Compliance'}
function renderReview(){let w=state.wizard,b=$('#wizardBody');setStep(2);b.innerHTML=`<h3>Review Suggested Tasks</h3><p>${w.suggestions.length?`Edit or remove any suggestion before adding it to Clipboard.`:'No tasks were selected. You can return to the questions or finish without adding anything.'}</p><div>${w.suggestions.map((t,i)=>`<div class=review-task><input type=checkbox checked id="keep${i}"><input type=text value="${esc(t.name)}" onchange="state.wizard.suggestions[${i}].name=this.value"><input type=date value="${t.due}" onchange="state.wizard.suggestions[${i}].due=this.value"></div>`).join('')}</div><div class=question-actions><button class=ghost onclick="restartQuestions()">Back to Questions</button><button class=primary onclick="addReviewed()">Add Selected Tasks</button><button class=linkbtn onclick="endWizard()">Skip to End</button></div>`}
window.restartQuestions=()=>{state.wizard.q=0;state.wizard.suggestions=[];renderWizard()};window.addReviewed=()=>{state.wizard.suggestions.forEach((t,i)=>{if($('#keep'+i)?.checked)state.tasks.push(t)});setStep(3);$('#wizardBody').innerHTML=`<h3>Tasks Added</h3><p>Your selected tasks are now in Clipboard and can be edited, rescheduled, or completed from the Task List.</p><button class=primary onclick="endWizard()">Go to Task List</button>`;render()};window.endWizard=()=>{$('.nav[data-view="tasks"]').click();state.wizard={event:null,q:0,answers:[],suggestions:[]};render()};function setStep(n){$$('.steps span').forEach((x,i)=>x.classList.toggle('on',i===n))}
$('#saveBtn').onclick=()=>{let blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='Codex_Clipboard_Project.json';a.click();URL.revokeObjectURL(a.href)};$('#openBtn').onclick=()=>$('#projectOpen').click();$('#projectOpen').onchange=async e=>{try{state=JSON.parse(await e.target.files[0].text());state.wizard={event:null,q:0,answers:[],suggestions:[]};render()}catch(x){alert('Could not open project file.')}};
loadLocal();render();renderWizard();
